version: "3.8"

services:
  favorites-mongodb:
    image: mongo:latest
    container_name: favorites-mongodb
    ports:
      - "27017:27017"

  favorites-service:
    build: .
    container_name: favorites-service
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URL=mongodb://favorites-mongodb:27017/favorites_db
    depends_on:
      - favorites-mongodb
